development:
  adapter:  postgresql
  encoding: unicode
  host:     db
  port:     5432
  username: postgres
  password: password
  database: sample_app_docker_development
  pool:     5

staging:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pool: 5
  database: <%= ENV['POSTGRESQL_DB'] %>